### PR TITLE
3 Improvements

### PR DESCRIPTION
**Pull request by HaujetZhao**
### Improvement1

We shouldn't analyze from the first audio frame of the audio 2 because the user may first pressed the Camera recording button and after few seconds, the Audio Recorder button is pressed then.
So we make a pre-shift to the audio2, analyzing a not-to-close-to-beginning audio clip.
If the child audio is shorter than 9min, it's 1/3 point is where the first analyzing-frame sets.
If the child audio is longer than 9 min, the 3min point is where the first analyzing-frame sets.

### Improvement2

Suppose we set the trim to 15min.
The former BBC solution can only analyze the first 15min of the mother audio
But if the audio and video are very long, the actual offset may be longer than 15min, say: 30min.
In this circumstance, we may not be able to get the correct offset.
So, it is needed to cut the mother audio into slices, whose length is 15min with a pre-offset of 60s.
Then we compare the child frames to the mother-clips one by one, until we get a qualified score.

### Improvement3

Made it easier and more convenient to use.

### CODE REVIEW

**Comment by abramhindle** [comment]
Sorry I missed this.

**Comment by nickteo** [comment]
I am using this library for a project of mine and I don't think that this PR makes this library better. It is now specialized to Haujet Zhao's usecase of replacing a video's audio with separately recorded audio whereas before it was a general purpose library to determine the offset of 1 piece of audio within another piece of audio. I would argue that Haujet should be forking this repository and specializing that fork to his usecase instead of submitting this change

**Comment by abramhindle** [comment]
@nickteo thanks for bringing this up. https://github.com/bbc/audio-offset-finder just got updated in a very professional manner. Perhaps that one would be better to use? If I have time I'm going to compare my prior version to their's and see if it is worth it. I think the BBC changed the MIR metrics they use.

**Comment by abramhindle** [comment]
@nickteo OK. I reverted it. I'll investigate later. But I think the updated BBC audio-offset-finder is really what you want.

**Comment by nickteo** [comment]
Great, thanks! I will also take a look. Thank you for your work on this library, it was great to unblock me as the previous version of the BBC library was not nearly as accurate as yours

**Pull request merged**
